### PR TITLE
Feature/new launch action interface

### PR DESCRIPTION
**Pull request by FGiraldez**
Main changes:

- Launch actions now publish their state (ActionState) through a fixed topic (name is a free_gait param). This provides feedback to the action loader.
-  C++ clients now also use the IDLE state. Any errors received in IDLE will just finish the action, without triggering an action error. 
- C++ servers can be blocked, not taking any more goals.
- Launch actions now stop (e.g. nodes die) when finished.

### CODE REVIEW

**Comment by remod** [comment]
Do we need this for CES?

**Comment by FGiraldez** [comment]
@remod I would say yes, if you do not want LP always running in the background.

**Comment by remod** [comment]
Ok thanks, let's try this branch tomorrow @pfankhauser

**Comment by FGiraldez** [comment]
Tested and working during CES. Will merge.

**Pull request merged**
